# syntax=docker/dockerfile:1
FROM ubuntu:latest

# Necessary for pwndbg
ENV LANG en_US.UTF-8
ENV LC_CTYPE C.UTF-8

RUN apt update

# Install umass-os requirements
RUN apt install -y build-essential gdb-multiarch qemu-system-misc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu

# Install dev requirements
RUN apt install -y tmux git
RUN echo "add-auto-load-safe-path /umass-os/.gdbinit" >> /root/.gdbinit

# Install pwndbg, not strictly speaking necessary. However, without it
# we'd need two different gdb scripts as gdb stops executing a script if 
# a command errors out. Since this container will be build once, reuse
# many times, seems easier to just install it.
RUN apt install -y python3 python3-pip
WORKDIR /opt
RUN git clone https://github.com/pwndbg/pwndbg
WORKDIR /opt/pwndbg
RUN ./setup.sh

# Install gdbgui
RUN apt install -y python3 python3-pip python3-venv
RUN python3 -m pip install pipx
RUN python3 -m userpath append ~/.local/bin
RUN pipx install gdbgui

EXPOSE 5000/tcp

WORKDIR /
ENTRYPOINT [ "/bin/bash" ]